name: deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install dependencies
        run: yarn
      - name: install vercel cli
        run: yarn global add vercel@latest
      - name: pull vercel env information
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
      - name: build artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: deploy to preview
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      - name: deploy to production
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
